name: iOS Build (Test Mode - No Code Signing)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios-test:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Build iOS app (No Code Signing)
      run: flutter build ios --release --no-codesign
      
    - name: Build iOS Archive (No Code Signing)
      run: flutter build ipa --release --no-codesign
      
    - name: Upload iOS Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ios-build-test
        path: |
          build/ios/ipa/*.ipa
          build/ios/Release-iphoneos/*.app
        retention-days: 7
        
    - name: Upload Build Logs
      uses: actions/upload-artifact@v3
      with:
        name: build-logs
        path: |
          build/ios/ios_build.log
        retention-days: 7
